name: Solor System yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*


env:
  MONGO_URI: ${{ secrets.MONGO_URI }}

jobs:
    unit-tests:
        strategy:
          fail-fast: true
          max-parallel: 2
          matrix:
            os-version: [18, 19, 20]
            os: [ubuntu-latest , macos-latest]
            exclude:
              - os: macos-latest
                os-version: 18
        runs-on: ${{ matrix.os }}
        steps: 
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Nodejs ${{ matrix.os-version }}
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.os-version }}

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

            - name: Upload test results
              uses: actions/upload-artifact@v4
              with:
                name: mocha-test-result-${{ matrix.os }}-${{ matrix.os-version }}
                path: test-results.xml

            
              
